# Generated by Django 5.2.3 on 2025-06-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
