# Generated by Django 5.2.3 on 2025-06-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="course",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Превью"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Превью"
            ),
        ),
    ]
