# Generated by Django 5.2.3 on 2025-06-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_subscriptioncourse"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="сумма покупки"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="сумма покупки"
            ),
        ),
    ]
